ALTER TABLE yah_survey_responses
ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';

ALTER TABLE yah_survey_responses
ADD COLUMN IF NOT EXISTS whatsapp TEXT NOT NULL DEFAULT '';

ALTER TABLE yah_survey_responses
ADD COLUMN IF NOT EXISTS consent BOOLEAN NOT NULL DEFAULT FALSE;
